baseURL = "https://vshaala.netlify.com/"
languageCode = "en-us"
title = "VShaala"
theme = "ananke"
themesDir = "../.."

SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"